#!/bin/bash

# Workaround for impish Nvidia discussed here:
#  - https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH#$SNAP_LIBRARY_PATH:}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${SNAP_LIBRARY_PATH}"

# Add additional path for KDEPlasmaPlatformTheme.so, until I can figure out how to move this to be with the other Qt plugins
export QT_PLUGIN_PATH=$QT_PLUGIN_PATH:$SNAP/kf5/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/plugins

# Add KF5 libexec directory containing kioslave5 for KDE file picker when not using portals
export PATH=$PATH:$KF5_LIBEXEC_DIR

# Use portals on GTK desktops but not on KDE because it seems to be buggy: https://forum.snapcraft.io/t/qt-snap-cant-select-a-folder-via-portal-file-picker-on-kde-but-can-on-gnome/27176/3
if [ $XDG_CURRENT_DESKTOP == "KDE" ]; then
  export QT_QPA_PLATFORMTHEME="kde"
fi

exec "${@}"
