name: citra-emu
base: core20
version: C2124-N1762
summary: Nintendo 3DS Emulator
description: "Citra is an experimental open-source Nintendo 3DS emulator/debugger written in C++. \nIt is written with portability in mind, with builds actively maintained for Windows, Linux and macOS.\n\nCitra emulates a subset of 3DS hardware and therefore is useful for running/debugging homebrew applications, and it is also able to run many commercial games! Some of these do not run at a playable state, \nbut work is being done every day to advance the project forward. (Playable here means compatibility of at least \"Okay\" on the game compatibility list.)\n\nCitra folder location: *`$HOME/snap/citra-emu/common/.local/share/citra-emu`*\n\nThis snap is not necessarily endorsed or officially maintained by the upstream developers.\n\nUpstream Project: https://citra-emu.org/\nsnapcraft.yaml Build Definition: https://github.com/Nightmayr/citra-snap/blob/master/snap/snapcraft.yaml\n\nDonate to citra: https://citra-emu.org/donate/\n"
license: GPL-2.0
icon: snap/gui/citra.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
compression: lzo
parts:
  citra-nightly:
    plugin: cmake
    source: https://github.com/citra-emu/citra-nightly.git
    source-tag: nightly-1762
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_QT_TRANSLATION=ON"
      - "-DUSE_DISCORD_PRESENCE=ON"
      - "-DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr/local/citra/nightly"
      - "-DENABLE_FFMPEG_AUDIO_DECODER=ON"
      - -DCMAKE_FIND_ROOT_PATH=/usr\;/root/stage\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current
    build-snaps:
      - kde-frameworks-5-qt-5-15-3-core20-sdk
    build-packages:
      - pkg-config
      - dpkg-dev
      - build-essential
      - libsdl2-dev
      - libpulse-dev
      - libavcodec-dev
      - libavcodec-extra
      - ffmpeg
      - libfdk-aac-dev
      - libssl-dev
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/removedirtyversion.patch
    build-environment:
      # These environment variables are used to replicate the Citra Travis CI build server environment, allowing the title bar to show the version
      - CI: "true"
      - TRAVIS: "true"
      - TRAVIS_TAG: nightly-1762
      - TRAVIS_REPO_SLUG: "citra-emu/citra-nightly"
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=citra|Icon=/usr/local/citra/nightly/share/icons/hicolor/scalable/apps/citra.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/citra/nightly/share/applications/citra.desktop
      sed -i 's|Name=Citra|Name=Citra Nightly|' $SNAPCRAFT_PART_INSTALL/usr/local/citra/nightly/share/applications/citra.desktop
    stage:
      - -usr/share/doc
    after:
      - patches
  citra-canary:
    plugin: cmake
    source: https://github.com/citra-emu/citra-canary.git
    source-tag: canary-2124
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_QT_TRANSLATION=ON"
      - "-DUSE_DISCORD_PRESENCE=ON"
      - "-DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr/local/citra/canary"
      - "-DENABLE_FFMPEG_AUDIO_DECODER=ON"
      - -DCMAKE_FIND_ROOT_PATH=/usr\;/root/stage\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current
    build-packages:
      - pkg-config
      - dpkg-dev
      - build-essential
      - libsdl2-dev
      - libpulse-dev
      - libavcodec-dev
      - libavcodec-extra
      - ffmpeg
      - libfdk-aac-dev
      - libssl-dev
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/removedirtyversion.patch
    build-environment:
      - CI: "true"
      - TRAVIS: "true"
      - TRAVIS_TAG: canary-2124
      - TRAVIS_REPO_SLUG: "citra-emu/citra-canary"
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=citra|Icon=/usr/local/citra/canary/share/icons/hicolor/scalable/apps/citra.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/citra/canary/share/applications/citra.desktop
      sed -i 's|Name=Citra|Name=Citra Canary|' $SNAPCRAFT_PART_INSTALL/usr/local/citra/canary/share/applications/citra.desktop
    stage:
      - -usr/share/doc
    after:
      - patches
      - citra-nightly
  patches:
    plugin: dump
    source: snap/local/patches
    source-type: local
    prime:
      - -*
  launchers:
    plugin: dump
    source: snap/local/launchers
    source-type: local
    organize:
      '*': bin/
  kde-neon-extension:
    build-packages:
      - g++
    build-snaps:
      - kde-frameworks-5-qt-5-15-3-core20-sdk/latest/candidate
    make-parameters:
      - PLATFORM_PLUG=nightmayr-kf5-qt-5-15-2-core20
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: kde-neon
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME="$SNAP_USER_DATA|XDG_DATA_HOME="$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i 's|XDG_CONFIG_HOME="$SNAP_USER_DATA|XDG_CONFIG_HOME="$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
  cleanup:
    after:
      - kde-neon-extension
      - citra-canary
      - citra-nightly
      - launchers
    plugin: nil
    build-snaps:
      - core20
      - nightmayr-kf5-qt-5-15-2-core20
    override-prime: |
      set -eux
      for snap in "core20" "nightmayr-kf5-qt-5-15-2-core20"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  citra-qt-nightly:
    command: usr/local/citra/nightly/bin/citra-qt
    command-chain:
      - "snap/command-chain/desktop-launch"
      - "bin/citra-launch"
    desktop: usr/local/citra/nightly/share/applications/citra.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - audio-record
      - opengl
      - joystick
      - unity7
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
  citra-qt-canary:
    command: usr/local/citra/canary/bin/citra-qt
    command-chain:
      - "snap/command-chain/desktop-launch"
      - "bin/citra-launch"
    desktop: usr/local/citra/canary/share/applications/citra.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - audio-record
      - opengl
      - joystick
      - unity7
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
  citra-canary:
    command: usr/local/citra/canary/bin/citra
    command-chain:
      - "bin/citra-launch"
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/kf5/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib:$SNAP/kf5/lib:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      DISABLE_WAYLAND: 1
      PATH: "$PATH:$SNAP/kf5/usr/bin:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
    plugs:
      - x11
      - wayland
      - audio-playback
      - audio-record
      - opengl
      - joystick
      - network
      - network-bind
      - home
      - removable-media
      - hardware-observe
      - mount-observe
  citra-nightly:
    command: usr/local/citra/nightly/bin/citra
    command-chain:
      - "bin/citra-launch"
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/kf5/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib:$SNAP/kf5/lib:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      DISABLE_WAYLAND: 1
      PATH: "$PATH:$SNAP/kf5/usr/bin:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
    plugs:
      - x11
      - wayland
      - audio-playback
      - audio-record
      - opengl
      - joystick
      - network
      - network-bind
      - home
      - removable-media
      - hardware-observe
      - mount-observe
  citra-room-canary:
    command: usr/local/citra/canary/bin/citra-room
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/kf5/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib:$SNAP/kf5/lib:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      DISABLE_WAYLAND: 1
      PATH: "$PATH:$SNAP/kf5/usr/bin:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
    plugs:
      - network
      - network-bind
      - home
  citra-room-nightly:
    command: usr/local/citra/nightly/bin/citra-room
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/kf5/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/kf5/usr/lib:$SNAP/kf5/lib:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      DISABLE_WAYLAND: 1
      PATH: "$PATH:$SNAP/kf5/usr/bin:$SNAP/kf5/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
    plugs:
      - network
      - network-bind
      - home
assumes:
  - snapd2.43
plugs:
  desktop:
    mount-host-font-cache: false
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  nightmayr-kf5-qt-5-15-2-core20:
    default-provider: nightmayr-kf5-qt-5-15-2-core20
    interface: content
    target: $SNAP/kf5
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/kf5
hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-desktop
    plugs:
      - desktop
