name: Build-Snap-Edge

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Testing snap
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        snap run citra-emu.citra-canary --version
        snap run citra-emu.citra-nightly --version
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: edge
