name: Build-Snap-Edge

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - uses: snapcore/action-build@v1.1.0
      id: snapcraft
    - name: Testing snap
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        sudo snap connect citra-emu:nightmayr-kf5-qt-5-15-2-core20 nightmayr-kf5-qt-5-15-2-core20
        snap run citra-emu.citra-canary --version
        snap run citra-emu.citra-nightly --version
    - uses: snapcore/action-publish@v1.1.1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: edge
